import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "SM Tech",
  description: "Generated by SM Tech",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={``}>
      <body>{children}
        
      </body>
    </html>
  );
}
